linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

issues:
  exclude-dirs:
    - vendor

run:
  timeout: 5m
  tests: false

linters-settings:
  errcheck:
    exclude-functions:
      - encoding/binary.Write
      - io.WriteString
